/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.ucsd.cse110.zooseeker.assets_example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void compiler_isnt_having_a_bad_day() {
        assertEquals(2, 1+1);
    }
}
